const allExchanges = [
  {
    code: "AX",
    name: "AUSTRALIAN ASX",
    country: "Australia",
    countryCode: "AU",
    tradingViewCode: "ASX",
  },
  {
    code: "CN",
    name: "CANADIAN NATIONAL STOCK EXCHANGE",
    country: "Canada",
    countryCode: "CA",
    tradingViewCode: "CSE",
  },
  {
    code: "DE",
    name: "XETRA",
    country: "Germany",
    countryCode: "DE",
    tradingViewCode: "XETR",
  },
  {
    code: "IS",
    name: "BORSA ISTANBUL",
    country: "Turkey",
    countryCode: "TR",
    tradingViewCode: "BIST",
  },
  {
    code: "JK",
    name: "INDONESIA STOCK EXCHANGE",
    country: "Indonesia",
    countryCode: "ID",
    tradingViewCode: "IDX",
  },
  {
    code: "KS",
    name: "KOREA EXCHANGE (STOCK MARKET)",
    country: "Korea",
    countryCode: "KR",
    tradingViewCode: "KRX",
  },
  {
    code: "L",
    name: "LONDON STOCK EXCHANGE",
    country: "United Kingdom",
    countryCode: "GB",
    tradingViewCode: "LSE",
  },
  {
    code: "MI",
    name: "Italian Stock Exchange",
    country: "Italy",
    countryCode: "IT",
    tradingViewCode: "MIL",
  },
  {
    code: "NE",
    name: "AEQUITAS NEO EXCHANGE",
    country: "Canada",
    countryCode: "CA",
    tradingViewCode: "NEO",
  },
  {
    code: "SG",
    name: "BOERSE STUTTGART",
    country: "Germany",
    countryCode: "DE",
    tradingViewCode: "SWB",
  },
  {
    code: "SS",
    name: "SHANGHAI STOCK EXCHANGE",
    country: "China",
    countryCode: "CN",
    tradingViewCode: "SSE",
  },
  {
    code: "SW",
    name: "SWISS EXCHANGE",
    country: "Switzerland",
    countryCode: "CH",
    tradingViewCode: "SIX",
  },
  {
    code: "SZ",
    name: "SHENZHEN STOCK EXCHANGE",
    country: "China",
    countryCode: "CN",
    tradingViewCode: "SZSE",
  },
  {
    code: "T",
    name: "TOKYO STOCK EXCHANGE-TOKYO PRO MARKET",
    country: "Japan",
    countryCode: "JP",
    tradingViewCode: "TOCOM",
  },
  {
    code: "TA",
    name: "TEL AVIV STOCK EXCHANGE",
    country: "Isreal",
    countryCode: "IL",
    tradingViewCode: "TASE",
  },
  {
    code: "TO",
    name: "TORONTO STOCK EXCHANGE",
    country: "Canada",
    countryCode: "CA",
    tradingViewCode: "TSX",
  },
  {
    code: "US",
    name: "US Exchange",
    country: "United States",
    countryCode: "US",
    tradingViewCode: "NYSE",
  },
  {
    code: "V",
    name: "TSX VENTURE EXCHANGE",
    country: "Canada",
    countryCode: "CA",
    tradingViewCode: "TSXV",
  },
  {
    code: "VN",
    name: "Vietnam Exchange",
    country: "Vietnam",
    countryCode: "VN",
    tradingViewCode: "HNX",
  },
  {
    code: "WA",
    name: "WARSAW STOCK EXCHANGE",
    country: "Poland",
    countryCode: "PL",
    tradingViewCode: "GPW",
  },
];

module.exports = { allExchanges };
